# This is a sample build configuration for Docker.
# Check our guides at https://confluence.atlassian.com/x/O1toN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassian/default-image:2

pipelines:
   pull-requests:
        '**':
          - step:
              name: Build and test
              services:
                - docker
              script:
              - echo "starting build"
              - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
              - docker pull 123459096/first-repo:pull_request_process_image
              - docker run -d -e BITBUCKET_COMMIT=$BITBUCKET_COMMIT -e BITBUCKET_PR_DESTINATION_BRANCH=$BITBUCKET_PR_DESTINATION_BRANCH -e BITBUCKET_BRANCH=$BITBUCKET_BRANCH -e BITBUCKET_REPO_SLUG=$BITBUCKET_REPO_SLUG -e BITBUCKET_PR_ID=$BITBUCKET_PR_ID --name pull_request_image 123459096/first-repo:pull_request_process_image
              - docker ps -aq -f status=running -f name=pull_request_image
              - while [ $(docker ps -aq -f status=running -f name=pull_request_image) ]; do   echo Executing checks; sleep 5; done
              - docker ps -aq -f status=running -f name=pull_request_image
              - docker logs pull_request_image
              - echo "Ending pipeline"
