# This a basic workflow to help you get started with Actions

name: CI to Docker Hub

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ develop, rapid-release, rapid-production ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create-deployment-artifacts:
      name: Create deployment artifacts
      runs-on: self-hosted
      outputs:
        deployment-matrix: ${{ steps.export-deployment-matrix.outputs.deployment-matrix }}
      steps:
        - uses: actions/checkout@v2
          with:
            ref: ykapare_test_branch1
          
        - name: Export deployment matrix
          id: export-deployment-matrix
          run: |
            JSON="$(cat ./deployment-config.json)"
            JSON="${JSON//'%'/'%25'}"
            JSON="${JSON//$'\n'/'%0A'}"
            JSON="${JSON//$'\r'/'%0D'}"
            echo "::set-output name=deployment-matrix::$JSON"  
  prepare-release-on-servers:
      name: "${{ matrix.server.name }}: Prepare release"
      runs-on: self-hosted
      needs: create-deployment-artifacts
      strategy:
        matrix:
          server: ${{ fromJson(needs.create-deployment-artifacts.outputs.deployment-matrix) }}
      steps:
        - name: run loop
          env:
            key: ${{ matrix.server.name }}
          run: |
            echo "First parameter: ${{ matrix.server.name }}"
            echo "server_name ${{ secrets[matrix.server.name] }}"
            echo "server_ip ${{ matrix.server.ip }}"
        
