# This is a basic workflow to help you get started with Actions

name: CI to Docker Hub

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: pull image
        id: docker_pull
        run:  |
		  docker pull 123459096/first-repo:pull_request_process_image
		  echo 'Bitbucket commit : ' . $GITHUB_SHA . '  Destination_Branch : ' . $GITHUB_HEAD_REF . '  Source_Branch: ' . $GITHUB_BASE_REF . '  Repo_Name : ' . $GITHUB_REPOSITORY . '  PR_ID' . $GITHUB_REF
		  docker run -d -e BITBUCKET_COMMIT=$GITHUB_SHA -e BITBUCKET_PR_DESTINATION_BRANCH=$GITHUB_HEAD_REF -e BITBUCKET_BRANCH=$GITHUB_BASE_REF -e BITBUCKET_REPO_SLUG=$GITHUB_REPOSITORY -e BITBUCKET_PR_ID=$GITHUB_REF  --name pull_request_image 123459096/first-repo:pull_request_process_image
		  docker ps -aq -f status=running -f name=pull_request_image
		  while [ $(docker ps -aq -f status=running -f name=pull_request_image) ]; do   echo Executing checks; sleep 5; done
		  docker ps -aq -f status=running -f name=pull_request_image
		  docker logs pull_request_image
		  echo "Ending pipeline"
		run: echo 'Done-----'  

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
